version: '3.9'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/clientDB

  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
